name: Smoke test

on: [ pull_request ]

jobs:
  smoke_test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setting up Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install openvino-dev[tensorflow2]==2022.2.0

      - name: Run smoke test
        run: cd test/smoke_test && ./run_smoke_test.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: results.csv
          path: test/smoke_test/results.csv
          retention-days: 1
