name: Smoke test

on: [ pull_request ]

jobs:
  smoke_test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setting up Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install openvino-dev[caffe,tensorflow2]==2022.2.0

      - name: Run smoke test for inference benchmark
        run: cd test/smoke_test && ./run_bench_smoke_test.sh

      - name: Run smoke test for accuracy checker
        run: cd test/smoke_test && ./run_ac_smoke_test.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: test/smoke_test/results*.csv
          retention-days: 1
